kind: pipeline
name: default

steps:
- name: test
  image: php
  commands:
  - "php -r \"copy('https://getcomposer.org/installer', 'composer-setup.php');\""
  - php composer-setup.php --install-dir=/usr/bin --filename=composer
  - "php -r \"unlink('composer-setup.php');\""
  - composer install --prefer-dist
  - php vendor/bin/phpunit

trigger:
  branch:
  - master