<?php

namespace App\Dto;

/**
 * This is autogenerated object, please not't touch it.
 *
 * @version 0.1.0
 */
final class Address
{
	/**
	 * Адрес строкой
	 *
	 * @var string
	 */
	public $inline;

	/**
	 * Области в которые входит обьект
	 *
	 * @Symfony\Component\Validator\Constraints\Valid()
	 * @var string[]
	 */
	public $provinces = [];
}

