<?php

namespace App\Dto;

/**
 * This is autogenerated object, please not't touch it.
 *
 * @version 0.1.0
 */
final class BankRequest
{
	/**
	 * @var BankRequestProductInterface|Mortgage|Refinancing
	 */
	public $product;

	/**
	 * @var int
	 */
	public $bankId;

	/**
	 * @var string
	 */
	public $bankSlug;

	/**
	 * @var int
	 */
	public $creditId;

	/**
	 * @var int
	 */
	public $id;


	/**
	 * @var BankRequestProductInterface $product
	 *
	 * @return BankRequest
	 */
	public function setProduct(BankRequestProductInterface $product): BankRequest
	{
		$this->product = $product;

		return $this;
	}
}

