<?php

namespace App\Dto;

/**
 * This is autogenerated object, please not't touch it.
 *
 * @version 0.1.0
 */
final class Bank
{
	/**
	 * Название банка
	 *
	 * @var string
	 *
	 * @Symfony\Component\Validator\Constraints\NotNull()
	 */
	public $name;

	/**
	 * Алиас банка
	 *
	 * @var string
	 *
	 * @Symfony\Component\Validator\Constraints\Choice(choices={"unicredit","sovkombank","metallinvest","gazprom","domrf","deltacredit"})
	 */
	public $slug;

	/**
	 * Процент партнёрского вознаграждения от выданных заёмных средств
	 *
	 * @var float
	 */
	public $partnerRewardPercent;

	/**
	 * Путь к логотипу
	 *
	 * @var string
	 */
	public $logo;

	/**
	 * Цвет плашки на фронте
	 *
	 * @var string
	 */
	public $color;

	/**
	 * @var int
	 */
	public $id;
}

