<?php

namespace App\Dto;

/**
 * This is autogenerated object, please not't touch it.
 *
 * @version 0.1.0
 *
 * @Symfony\Component\Serializer\Annotation\DiscriminatorMap(typeProperty="type", mapping={
 *     "mortgage" = Mortgage::class,
 *     "refinancing" = Refinancing::class
 * })
 */
interface BankRequestProductInterface
{
}

