<?php

namespace App\Dto;

/**
 * This is autogenerated object, please not't touch it.
 *
 * @version 0.1.0
 */
final class CalculateContainer
{
	/**
	 * @var Bank
	 */
	public $bank;

	/**
	 * @var Resolution
	 */
	public $resolution;

	/**
	 * Вознаграждение партнёра
	 *
	 * @var float
	 */
	public $partnerReward;
}

