<?php

namespace App\Dto;

/**
 * This is autogenerated object, please not't touch it.
 *
 * @version 0.1.0
 */
final class Credit
{
	/**
	 * Процентная ставка
	 *
	 * @var float
	 */
	public $percentRate;

	/**
	 * Ежемесячный платёж
	 *
	 * @var float
	 */
	public $monthlyPayment;

	/**
	 * Полная сумма с учётом переплат
	 *
	 * @var int
	 */
	public $totalSum;

	/**
	 * Сумма заёмных средств
	 *
	 * @var int
	 */
	public $creditSum;

	/**
	 * Размер первоначального взноса
	 *
	 * @var int
	 */
	public $initialPayment;

	/**
	 * Срок кредита (в мес.)
	 *
	 * @var int
	 */
	public $creditPeriod;

	/**
	 * Результирующая переплата по кредиту
	 *
	 * @var int
	 */
	public $overpayment;
}

