<?php

namespace App\Dto;

/**
 * This is autogenerated object, please not't touch it.
 *
 * @version 0.1.0
 */
final class CreditRequest
{
	/**
	 * @Symfony\Component\Validator\Constraints\Valid()
	 * @var BankRequest[]
	 */
	public $requests = [];

	/**
	 * @var int
	 */
	public $id;


	/**
	 * @var BankRequest $request
	 *
	 * @return CreditRequest
	 */
	public function addRequest(BankRequest $request): CreditRequest
	{
		if (!in_array($request, $this->requests, true)) {
		    $this->requests = $request;
		}

		return $this;
	}


	/**
	 * @var BankRequest $request
	 *
	 * @return CreditRequest
	 */
	public function removeRequest(BankRequest $request): CreditRequest
	{
		if (false !== $index = array_search($request, $this->requests, true)) {
		    unset($this->requests[$index]);
		}

		return $this;
	}
}

