<?php

namespace App\Dto;

/**
 * This is autogenerated object, please not't touch it.
 *
 * @version 0.1.0
 */
final class Document
{
	/**
	 * Тип документа
	 *
	 * @var string
	 */
	public $type;

	/**
	 * @var string
	 */
	public $title;

	/**
	 * @var string
	 */
	public $description;

	/**
	 * ID файлов
	 *
	 * @Symfony\Component\Validator\Constraints\Valid()
	 * @var int[]
	 */
	public $files = [];

	/**
	 * @var int
	 */
	public $id;
}

