<?php

namespace App\Dto;

/**
 * This is autogenerated object, please not't touch it.
 *
 * @version 0.1.0
 */
final class LeadParticipant
{
	/**
	 * @var int|null
	 */
	public $personId;

	/**
	 * Роль в сделке
	 *
	 * @var string
	 *
	 * @Symfony\Component\Validator\Constraints\Choice(choices={"borrower","coBorrower","guarantor"})
	 */
	public $role;

	/**
	 * Возраст
	 *
	 * @var int
	 */
	public $age;

	/**
	 * Имя
	 *
	 * @var string
	 */
	public $firstName;

	/**
	 * Фамилия
	 *
	 * @var string
	 */
	public $lastName;

	/**
	 * Отчество
	 *
	 * @var string
	 */
	public $patronymic;

	/**
	 * Номер телефона
	 *
	 * @var string
	 */
	public $phoneNumber;

	/**
	 * Почтовый адрес
	 *
	 * @var string
	 */
	public $email;

	/**
	 * Контактное лицо
	 *
	 * @var bool
	 */
	public $contactPerson;

	/**
	 * Семейное положение
	 *
	 * @var string
	 *
	 * @Symfony\Component\Validator\Constraints\Choice(choices={"single","married"})
	 */
	public $maritalStatus;

	/**
	 * Брачный контракт
	 *
	 * @var bool
	 */
	public $marriageContract;

	/**
	 * Гражданство
	 *
	 * @var string
	 *
	 * @Symfony\Component\Validator\Constraints\Choice(choices={"russia","other"})
	 */
	public $citizenship;

	/**
	 * Регистрация
	 *
	 * @var string
	 *
	 * @Symfony\Component\Validator\Constraints\Choice(choices={"permanent","temporary"})
	 */
	public $registrationType;

	/**
	 * Есть вид на жительство?
	 *
	 * @var bool
	 */
	public $residencePermit;

	/**
	 * Супруг
	 *
	 * @var bool
	 */
	public $spouse;

	/**
	 * Налоговый нерезидент РФ
	 *
	 * @var bool
	 */
	public $taxResidentRF;

	/**
	 * Участвует в выплатах
	 *
	 * @var bool
	 */
	public $involvedInPayment;

	/**
	 * Тип занятости
	 *
	 * @var string
	 *
	 * @Symfony\Component\Validator\Constraints\NotNull()
	 * @Symfony\Component\Validator\Constraints\Choice(choices={"recruitment","individual_entrepreneur","business"})
	 */
	public $jobType;

	/**
	 * Документ подтвержающий доход
	 *
	 * @var string
	 *
	 * @Symfony\Component\Validator\Constraints\Choice(choices={"2ndfl","bankForm","2docs"})
	 */
	public $proofOfIncome;

	/**
	 * Адвокат или нотариус
	 *
	 * @var bool
	 */
	public $lawyerOrNotary;

	/**
	 * Сотрудник силовых структур
	 *
	 * @var bool
	 */
	public $military;

	/**
	 * Стаж на последнем месте работы (мес)
	 *
	 * @var int
	 */
	public $lastExperience;

	/**
	 * Общий стаж
	 *
	 * @var int
	 */
	public $generalExperience;

	/**
	 * Срок владения бизнесом (мес.)
	 *
	 * @var int
	 */
	public $tenureOfBusiness;

	/**
	 * Процент владения бизнесом
	 *
	 * @var float
	 */
	public $percentOfBusiness;
}

