<?php

namespace App\Dto;

/**
 * This is autogenerated object, please not't touch it.
 *
 * @version 0.1.0
 */
final class Participant
{
	/**
	 * @var int
	 */
	public $personId;

	/**
	 * Участвует в выплатах
	 *
	 * @var bool
	 */
	public $involvedInPayment;

	/**
	 * Роль в сделке
	 *
	 * @var string
	 *
	 * @Symfony\Component\Validator\Constraints\Choice(choices={"borrower","coBorrower","guarantor"})
	 */
	public $role;

	/**
	 * Фамилия
	 *
	 * @var string
	 */
	public $lastName;

	/**
	 * Имя
	 *
	 * @var string
	 */
	public $firstName;

	/**
	 * Отчество
	 *
	 * @var string
	 */
	public $patronymic;

	/**
	 * Возраст (полных лет)
	 *
	 * @var int
	 */
	public $age;

	/**
	 * Семейное положение
	 *
	 * @var string
	 *
	 * @Symfony\Component\Validator\Constraints\Choice(choices={"single","married"})
	 */
	public $maritalStatus;

	/**
	 * Есть брачный договор?
	 *
	 * @var bool
	 */
	public $marriageContract;

	/**
	 * Гражданство
	 *
	 * @var string
	 *
	 * @Symfony\Component\Validator\Constraints\Choice(choices={"russia","other"})
	 */
	public $citizenship;

	/**
	 * Регистрация
	 *
	 * @var string
	 *
	 * @Symfony\Component\Validator\Constraints\Choice(choices={"mortgage","refinancing"})
	 */
	public $registrationType;

	/**
	 * Есть вид на жительство?
	 *
	 * @var bool
	 */
	public $residencePermit;

	/**
	 * Трудоустройство
	 *
	 * @var string
	 *
	 * @Symfony\Component\Validator\Constraints\Choice(choices={"recruitment","individual_entrepreneur","business"})
	 */
	public $jobType;

	/**
	 * Тип договора (трудовой, гпх)
	 *
	 * @var string
	 *
	 * @Symfony\Component\Validator\Constraints\Choice(choices={"employment","gph"})
	 */
	public $jobContractType;

	/**
	 * Адвокат или нотариус?
	 *
	 * @var bool
	 */
	public $lawyerOrNotary;

	/**
	 * Военнообязаный?
	 *
	 * @var bool
	 */
	public $military;

	/**
	 * Есть работа по совместительству?
	 *
	 * @var bool
	 */
	public $partTimeJob;

	/**
	 * Подтверждение дохода
	 *
	 * @var string
	 *
	 * @Symfony\Component\Validator\Constraints\Choice(choices={"2ndfl","bankForm","2docs"})
	 */
	public $proofOfIncome;

	/**
	 * Стаж на последнем месте работы (мес)
	 *
	 * @var int
	 */
	public $lastExperience;

	/**
	 * Общий стаж (мес)
	 *
	 * @var int
	 */
	public $generalExperience;

	/**
	 * Срок владения ИП или бизнесом (мес.)
	 *
	 * @var int
	 */
	public $tenureOfBusiness;

	/**
	 * Процент владения бизнесом
	 *
	 * @var float
	 */
	public $percentOfBusiness;

	/**
	 * Есть просрочки по текущим кредитам?
	 *
	 * @var bool
	 */
	public $overduePayment;

	/**
	 * Налоговый резидент РФ?
	 *
	 * @var bool
	 */
	public $taxResidentRF;

	/**
	 * Пол
	 *
	 * @var string
	 *
	 * @Symfony\Component\Validator\Constraints\Choice(choices={"male","female"})
	 */
	public $gender;

	/**
	 * Документы
	 *
	 * @Symfony\Component\Validator\Constraints\Valid()
	 * @var Document[]
	 */
	public $documents = [];


	/**
	 * @var Document $document
	 *
	 * @return Participant
	 */
	public function addDocument(Document $document): Participant
	{
		if (!in_array($document, $this->documents, true)) {
		    $this->documents = $document;
		}

		return $this;
	}


	/**
	 * @var Document $document
	 *
	 * @return Participant
	 */
	public function removeDocument(Document $document): Participant
	{
		if (false !== $index = array_search($document, $this->documents, true)) {
		    unset($this->documents[$index]);
		}

		return $this;
	}
}

