<?php

namespace App\Dto;

/**
 * This is autogenerated object, please not't touch it.
 *
 * @version 0.1.0
 */
final class Person
{
	/**
	 * ФИО
	 *
	 * @var string
	 */
	public $fullName;

	/**
	 * Фамилия
	 *
	 * @var string
	 */
	public $lastName;

	/**
	 * Имя
	 *
	 * @var string
	 *
	 * @Symfony\Component\Validator\Constraints\NotNull()
	 */
	public $firstName;

	/**
	 * Отчество
	 *
	 * @var string
	 */
	public $patronymic;

	/**
	 * Возраст (полных лет)
	 *
	 * @var int
	 */
	public $age;

	/**
	 * Семейное положение
	 *
	 * @var string
	 *
	 * @Symfony\Component\Validator\Constraints\Choice(choices={"single","married"})
	 */
	public $maritalStatus;

	/**
	 * Есть брачный контракт?
	 *
	 * @var bool
	 */
	public $marriageContract;

	/**
	 * Гражданство
	 *
	 * @var string
	 *
	 * @Symfony\Component\Validator\Constraints\Choice(choices={"russia","other"})
	 */
	public $citizenship;

	/**
	 * Регистрация (временная|постоянная)
	 *
	 * @var string
	 *
	 * @Symfony\Component\Validator\Constraints\Choice(choices={"permanent","temporary"})
	 */
	public $registrationType;

	/**
	 * Есть вид на жительство?
	 *
	 * @var bool
	 */
	public $residencePermit;

	/**
	 * Трудоустройсто (найм|ип\бизнес)
	 *
	 * @var string
	 *
	 * @Symfony\Component\Validator\Constraints\Choice(choices={"recruitment","individual_entrepreneur","business"})
	 */
	public $jobType;

	/**
	 * Договор найма (трудовой договор|ГПХ)
	 *
	 * @var string
	 *
	 * @Symfony\Component\Validator\Constraints\Choice(choices={"gph","employment"})
	 */
	public $jobContractType;

	/**
	 * Адвокат или нотариус?
	 *
	 * @var bool
	 */
	public $lawyerOrNotary;

	/**
	 * Военнообяан?
	 *
	 * @var bool
	 */
	public $military;

	/**
	 * Есть работа по совместительству?
	 *
	 * @var bool
	 */
	public $partTimeJob;

	/**
	 * Подтверждение дохода
	 *
	 * @var string
	 *
	 * @Symfony\Component\Validator\Constraints\Choice(choices={"2ndfl","bankForm","2docs"})
	 */
	public $proofOfIncome;

	/**
	 * Стаж на последнем месте работы (мес)
	 *
	 * @var int
	 */
	public $lastExperience;

	/**
	 * Общий стаж (мес)
	 *
	 * @var int
	 */
	public $generalExperience;

	/**
	 * Срок владения ИП или бизнесом (мес.)
	 *
	 * @var int
	 */
	public $tenureOfBusiness;

	/**
	 * Процент владения бизнесом
	 *
	 * @var float
	 */
	public $percentOfBusiness;

	/**
	 * Есть просрочки по текущим кредитам?
	 *
	 * @var bool
	 */
	public $overduePayment;

	/**
	 * Налоговый резидент РФ?
	 *
	 * @var bool
	 */
	public $taxResidentRF;

	/**
	 * Пол
	 *
	 * @var string
	 *
	 * @Symfony\Component\Validator\Constraints\Choice(choices={"male","female"})
	 */
	public $gender;

	/**
	 * Документы
	 *
	 * @Symfony\Component\Validator\Constraints\Valid()
	 * @var Document[]
	 */
	public $documents = [];

	/**
	 * @var int
	 */
	public $id;


	/**
	 * @var Document $document
	 *
	 * @return Person
	 */
	public function addDocument(Document $document): Person
	{
		if (!in_array($document, $this->documents, true)) {
		    $this->documents = $document;
		}

		return $this;
	}


	/**
	 * @var Document $document
	 *
	 * @return Person
	 */
	public function removeDocument(Document $document): Person
	{
		if (false !== $index = array_search($document, $this->documents, true)) {
		    unset($this->documents[$index]);
		}

		return $this;
	}
}

