<?php

namespace App\Dto;

/**
 * This is autogenerated object, please not't touch it.
 *
 * @version 0.1.0
 */
final class Resolution
{
	/**
	 * Дополнительная информация
	 *
	 * @Symfony\Component\Validator\Constraints\Valid()
	 * @var string[]
	 */
	public $info = [];

	/**
	 * Резолюция по данному лиду и банку
	 *
	 * @var string
	 *
	 * @Symfony\Component\Validator\Constraints\Choice(choices={"approved","rejected","unknown"})
	 */
	public $status;

	/**
	 * Причины отказа
	 *
	 * @Symfony\Component\Validator\Constraints\Valid()
	 * @var string[]
	 */
	public $reasons = [];

	/**
	 * @var Credit
	 */
	public $credit;

	/**
	 * Слаг банка
	 *
	 * @var string
	 */
	public $bankSlug;
}

