<?php

namespace App\Dto;

/**
 * This is autogenerated object, please not't touch it.
 *
 * @version 0.1.0
 */
final class User
{
	/**
	 * @var int
	 */
	public $id;

	/**
	 * @var string
	 */
	public $firstName;

	/**
	 * @var string
	 */
	public $lastName;

	/**
	 * @var string
	 */
	public $patronymic;

	/**
	 * @var string
	 */
	public $email;

	/**
	 * @var string
	 */
	public $phoneNumber;

	/**
	 * @var bool
	 */
	public $active;

	/**
	 * @Symfony\Component\Validator\Constraints\Valid()
	 * @var string[]
	 */
	public $roles = [];
}

